version: "3.8"

services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  test:
    build: .
    container_name: fastapi_test
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["pytest", "--maxfail=1", "--disable-warnings", "-v"]

volumes:
  postgres_data: